# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  glider_config = release
endif
ifeq ($(config),debug)
  glider_config = debug
endif

PROJECTS := glider

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

glider:
ifneq (,$(glider_config))
	@echo "==== Building glider ($(glider_config)) ===="
	@${MAKE} --no-print-directory -C . -f glider.make config=$(glider_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f glider.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glider"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"